language: java
jdk:
- oraclejdk8

-install:
- mvn test -B
- mvn install -Dmaven.javadoc.skip=true -B -V

addons:
  sonarqube:
    organization: "305"
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
- sonar-scanner
